# Generated by Django 2.0.7 on 2018-07-09 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_hash', models.CharField(max_length=1024)),
                ('nonce', models.IntegerField(default=0)),
                ('hash', models.CharField(max_length=1024)),
                ('timestamp', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='BlockChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('sender', models.CharField(max_length=1024)),
                ('recipient', models.CharField(max_length=1024)),
                ('value', models.DecimalField(decimal_places=4, max_digits=24)),
                ('signature', models.CharField(max_length=1024)),
                ('id', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.Block')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_output_id', models.CharField(max_length=1024)),
                ('parent_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input', to='blockchain.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionOutput',
            fields=[
                ('recipient', models.CharField(max_length=1024)),
                ('value', models.DecimalField(decimal_places=4, max_digits=24)),
                ('id', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('spent', models.BooleanField()),
                ('parent_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output', to='blockchain.Transaction')),
            ],
        ),
        migrations.AddField(
            model_name='transactioninput',
            name='utxo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='utxo', to='blockchain.TransactionOutput'),
        ),
        migrations.AddField(
            model_name='block',
            name='blockchain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.BlockChain'),
        ),
    ]
