# Generated by Django 2.0 on 2018-07-10 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_count_on_block', models.IntegerField()),
                ('fee', models.DecimalField(decimal_places=4, max_digits=24)),
                ('reward', models.DecimalField(decimal_places=4, max_digits=24)),
                ('difficulty', models.IntegerField()),
                ('generate_token', models.CharField(max_length=100)),
                ('loan_condition', models.DecimalField(decimal_places=4, max_digits=24)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, 'customer'), (2, 'bank'), (3, 'manager')])),
                ('password', models.CharField(max_length=1000)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('salt', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='banking.Login')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.CharField(max_length=20)),
                ('pub', models.CharField(max_length=1024)),
                ('pv', models.CharField(max_length=1024)),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_bank', to='banking.Bank')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='login',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='banking.Login'),
        ),
        migrations.AddField(
            model_name='customer',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.Wallet'),
        ),
        migrations.AddField(
            model_name='bank',
            name='login',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='banking.Login'),
        ),
        migrations.AddField(
            model_name='bank',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_wallet', to='banking.Wallet'),
        ),
    ]
