# Generated by Django 2.0 on 2018-07-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='pv',
            field=models.CharField(max_length=3000),
        ),
    ]
