# Generated by Django 2.0.7 on 2018-07-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_auto_20180709_0355'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.IntegerField()),
                ('fee', models.DecimalField(decimal_places=4, max_digits=24)),
                ('reward', models.DecimalField(decimal_places=4, max_digits=24)),
                ('difficulty', models.IntegerField()),
                ('generate_token', models.CharField(max_length=100)),
                ('loan_condition', models.DecimalField(decimal_places=4, max_digits=24)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=1000)),
                ('salt', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
