# Generated by Django 2.0.7 on 2018-07-09 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_banksettings_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='id',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='password',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='salt',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='username',
        ),
        migrations.AddField(
            model_name='manager',
            name='customer_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='banking.Customer'),
            preserve_default=False,
        ),
    ]
