# Generated by Django 2.0.7 on 2018-07-09 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_auto_20180709_0611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banksettings',
            old_name='transaction',
            new_name='transaction_count_on_block',
        ),
    ]
