# Generated by Django 2.0.7 on 2018-07-09 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_auto_20180709_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=1000)),
                ('username', models.CharField(max_length=100)),
                ('salt', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.CharField(max_length=20)),
                ('pub', models.CharField(max_length=1024)),
                ('pv', models.CharField(max_length=1024)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_bank', to='banking.Bank')),
            ],
        ),
        migrations.RemoveField(
            model_name='manager',
            name='customer_ptr',
        ),
        migrations.AddField(
            model_name='manager',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manager',
            name='password',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manager',
            name='salt',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manager',
            name='username',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_wallet', to='banking.Wallet'),
        ),
        migrations.AddField(
            model_name='customer',
            name='wallet',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='banking.Wallet'),
            preserve_default=False,
        ),
    ]
