# Generated by Django 2.0 on 2018-07-10 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0006_auto_20180709_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_bank', to='banking.Bank'),
        ),
    ]
