# Generated by Django 2.0.7 on 2018-07-10 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0007_auto_20180710_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='token',
        ),
        migrations.AlterField(
            model_name='bank',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_wallet', to='banking.Wallet'),
        ),
    ]
