# Generated by Django 2.0.7 on 2018-07-10 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0009_auto_20180710_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=1000)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('salt', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='bank',
            name='id',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='password',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='salt',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='username',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='salt',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='id',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='password',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='salt',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='username',
        ),
        migrations.AddField(
            model_name='bank',
            name='login_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='banking.Login'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='login_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='banking.Login'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manager',
            name='login_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='banking.Login'),
            preserve_default=False,
        ),
    ]
