# Generated by Django 2.0.7 on 2018-07-10 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0010_auto_20180710_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='login_ptr',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='login_ptr',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='login_ptr',
        ),
        migrations.AddField(
            model_name='bank',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank',
            name='login',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='banking.Login'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='login',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='banking.Login'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manager',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manager',
            name='login',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='banking.Login'),
            preserve_default=False,
        ),
    ]
