# Generated by Django 2.0.7 on 2018-07-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0011_auto_20180710_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'customer'), (2, 'bank'), (3, 'manager')], default=0),
            preserve_default=False,
        ),
    ]
